services:
      app:
        build: .
        ports: 
            - "8000:8000"
        environment:
            APP_NAME: Orderflow-backend
            ENVIRONMENT: local
            DATABASE_URL: postgresql+psycopg://orderflow:orderflow_password@db:5432/orderflow
        depends_on:
            - db
        #volume: # пока не нужен

      db:
        image: postgres:18
        environment:
          POSTGRES_USER: orderflow
          POSTGRES_PASSWORD: orderflow_password
          POSTGRES_DB: orderflow
        ports:
            - "55432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql

volumes:
    postgres_data:
