"""add order data constraints

Revision ID: 23e12ecf52fc
Revises: dd7e0d60b7d7
Create Date: 2026-07-31 20:09:30.214183

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '23e12ecf52fc'
down_revision: str | None = 'dd7e0d60b7d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "title",
        existing_type=sa.String(),
        type_=sa.String(length=255),
        existing_nullable=False,
    )

    op.create_check_constraint(
        "ck_orders_title_not_empty",
        "orders",
        "title <> ''",
    )

    op.create_check_constraint(
        "ck_orders_title_trimmed",
        "orders",
        r"title = btrim(title, E' \t\n\r\f' || chr(11))",
    )

    op.create_check_constraint(
        "ck_orders_status_allowed",
        "orders",
        "status IN ('new', 'processing', 'canceled', 'completed')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_orders_title_not_empty",
        "orders",
        type_="check",
    )
    op.drop_constraint(
        "ck_orders_title_trimmed",
        "orders",
        type_="check",
    )
    op.drop_constraint(
        "ck_orders_status_allowed",
        "orders",
        type_="check",
    )

    op.alter_column(
        "orders",
        "title",
        existing_type=sa.String(length=255),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
