"""add order items order_id index

Revision ID: 8387b342c143
Revises: a592177b7a6d
Create Date: 2026-08-28 19:33:10.506812

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8387b342c143'
down_revision: str | None = 'a592177b7a6d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_order_items_order_id'),
        'order_items',
        ['order_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_order_items_order_id'),
        table_name='order_items'
    )
    # ### end Alembic commands ###
