"""empty message

Revision ID: a592177b7a6d
Revises: 23e12ecf52fc
Create Date: 2026-08-14 18:10:34.637750

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a592177b7a6d'
down_revision: str | None = '23e12ecf52fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=400), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint(
        "product_name <> ''",
        name='ck_order_items_product_name_not_empty'
    ),
    sa.CheckConstraint(
        "product_name = btrim(product_name, E' \\t\\n\\r\\f' || chr(11))",
        name='ck_order_items_product_name_trimmed'
    ),
    sa.CheckConstraint('quantity > 0', name='ck_order_items_quantity_positive'),
    sa.CheckConstraint('unit_price > 0', name='ck_order_items_unit_price_positive'),
    sa.ForeignKeyConstraint(
        ['order_id'],
        ['orders.id'],
        ondelete='CASCADE'
    ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    # ### end Alembic commands ###
